// <auto-generated />
using System;
using Golfklubb_Centar_Webbshop.Areas.Identity.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Golfklubb_Centar_Webbshop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260306094804_TestingMigration")]
    partial class TestingMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("CentarUserMngt")
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Golfklubb_Centar_Webbshop.Areas.Identity.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Testing")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", "CentarUserMngt");
                });

            modelBuilder.Entity("Golfklubb_Centar_Webbshop.Models.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"));

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(7, 2)");

                    b.HasKey("CartId")
                        .HasName("PK_CartId");

                    b.ToTable("Carts", "CentarOrderMngt");
                });

            modelBuilder.Entity("Golfklubb_Centar_Webbshop.Models.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"));

                    b.Property<DateOnly>("AddedDate")
                        .HasColumnType("date");

                    b.Property<int>("FkCartId")
                        .HasColumnType("int")
                        .HasColumnName("FK_CartId");

                    b.Property<int>("FkProductId")
                        .HasColumnType("int")
                        .HasColumnName("FK_ProductId");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("CartItemId")
                        .HasName("PK_CartItemId");

                    b.HasIndex("FkCartId");

                    b.HasIndex("FkProductId");

                    b.ToTable("CartItems", "CentarOrderMngt");
                });

            modelBuilder.Entity("Golfklubb_Centar_Webbshop.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("FkParentCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("FK_ParentCategoryId");

                    b.HasKey("CategoryId")
                        .HasName("PK_CategoryId");

                    b.HasIndex("FkParentCategoryId");

                    b.ToTable("Categories", "CentarProductMngt");
                });

            modelBuilder.Entity("Golfklubb_Centar_Webbshop.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<string>("CommentContent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("CommentDateTime")
                        .HasColumnType("datetime");

                    b.Property<int>("FkPostId")
                        .HasColumnType("int")
                        .HasColumnName("FK_PostId");

                    b.Property<string>("FkUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("FK_UserId");

                    b.HasKey("CommentId")
                        .HasName("PK_CommentId");

                    b.HasIndex("FkPostId");

                    b.HasIndex("FkUserId");

                    b.ToTable("Comments", "CentarForumMngt");
                });

            modelBuilder.Entity("Golfklubb_Centar_Webbshop.Models.Discount", b =>
                {
                    b.Property<int>("DiscountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiscountId"));

                    b.Property<int>("Discount1")
                        .HasColumnType("int")
                        .HasColumnName("Discount");

                    b.Property<string>("DiscountDescribtion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("DiscountId")
                        .HasName("PK_DiscountId");

                    b.ToTable("Discounts", "CentarProductMngt");
                });

            modelBuilder.Entity("Golfklubb_Centar_Webbshop.Models.History", b =>
                {
                    b.Property<int>("OrderHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderHistoryId"));

                    b.Property<int>("FkInvoiceId")
                        .HasColumnType("int")
                        .HasColumnName("FK_InvoiceId");

                    b.Property<string>("FkUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("FK_UserId");

                    b.HasKey("OrderHistoryId")
                        .HasName("PK_OrderHistoryId");

                    b.HasIndex("FkInvoiceId");

                    b.HasIndex("FkUserId");

                    b.ToTable("Histories", "CentarOrderMngt");
                });

            modelBuilder.Entity("Golfklubb_Centar_Webbshop.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<int>("FkOrderId")
                        .HasColumnType("int")
                        .HasColumnName("FK_OrderId");

                    b.Property<int?>("FkPaymentId")
                        .HasColumnType("int")
                        .HasColumnName("FK_PaymentId");

                    b.Property<int>("FkTaxId")
                        .HasColumnType("int")
                        .HasColumnName("FK_TaxId");

                    b.Property<string>("FkUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("FK_UserId");

                    b.Property<DateTime>("OrderDateTime")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("PaymentDateTime")
                        .HasColumnType("datetime");

                    b.HasKey("InvoiceId")
                        .HasName("PK_InvoiceId");

                    b.HasIndex("FkOrderId");

                    b.HasIndex("FkPaymentId");

                    b.HasIndex("FkTaxId");

                    b.HasIndex("FkUserId");

                    b.ToTable("Invoices", "CentarOrderMngt");
                });

            modelBuilder.Entity("Golfklubb_Centar_Webbshop.Models.InvoiceItem", b =>
                {
                    b.Property<int>("InvoiceItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceItemId"));

                    b.Property<int?>("FkDiscountId")
                        .HasColumnType("int")
                        .HasColumnName("FK_DiscountId");

                    b.Property<int>("FkInvoiceId")
                        .HasColumnType("int")
                        .HasColumnName("FK_InvoiceId");

                    b.Property<int>("FkProductId")
                        .HasColumnType("int")
                        .HasColumnName("FK_ProductId");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(7, 2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(7, 2)");

                    b.HasKey("InvoiceItemId")
                        .HasName("PK_InvoiceItemId");

                    b.HasIndex("FkInvoiceId");

                    b.HasIndex("FkProductId");

                    b.ToTable("InvoiceItems", "CentarOrderMngt");
                });

            modelBuilder.Entity("Golfklubb_Centar_Webbshop.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("FkCartId")
                        .HasColumnType("int")
                        .HasColumnName("FK_CartId");

                    b.Property<string>("FkUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("FK_UserId");

                    b.Property<string>("OrderStatus")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("OrderId")
                        .HasName("PK_OrderId");

                    b.HasIndex("FkCartId");

                    b.HasIndex("FkUserId");

                    b.ToTable("Orders", "CentarOrderMngt");
                });

            modelBuilder.Entity("Golfklubb_Centar_Webbshop.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(7, 2)");

                    b.Property<int>("FkOrderId")
                        .HasColumnType("int")
                        .HasColumnName("FK_OrderId");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool?>("PaymentStatus")
                        .HasColumnType("bit");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("int");

                    b.HasKey("PaymentId")
                        .HasName("PK_PaymentId");

                    b.HasIndex("FkOrderId");

                    b.ToTable("Payments", "CentarOrderMngt");
                });

            modelBuilder.Entity("Golfklubb_Centar_Webbshop.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"));

                    b.Property<string>("FkUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("FK_UserId");

                    b.Property<string>("PostContent")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("PostCreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PostTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("PostId")
                        .HasName("PK_PostId");

                    b.HasIndex("FkUserId");

                    b.ToTable("Posts", "CentarForumMngt");
                });

            modelBuilder.Entity("Golfklubb_Centar_Webbshop.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("FkCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("FK_CategoryId");

                    b.Property<int>("FkDiscountId")
                        .HasColumnType("int")
                        .HasColumnName("FK_DiscountId");

                    b.Property<string>("ProductDescribtion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProductImgPath")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(7, 2)");

                    b.HasKey("ProductId")
                        .HasName("PK_ProductID");

                    b.HasIndex("FkCategoryId");

                    b.HasIndex("FkDiscountId");

                    b.ToTable("Products", "CentarProductMngt");
                });

            modelBuilder.Entity("Golfklubb_Centar_Webbshop.Models.ProductReview", b =>
                {
                    b.Property<int>("ProductReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductReviewId"));

                    b.Property<int>("FkProductId")
                        .HasColumnType("int")
                        .HasColumnName("FK_ProductId");

                    b.Property<string>("FkUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("FK_UserId");

                    b.Property<string>("ProductReviewContent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("ProductReviewId")
                        .HasName("PK_ProductReviewId");

                    b.HasIndex("FkProductId");

                    b.HasIndex("FkUserId");

                    b.ToTable("ProductReviews", "CentarProductMngt");
                });

            modelBuilder.Entity("Golfklubb_Centar_Webbshop.Models.Stock", b =>
                {
                    b.Property<int>("StockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockId"));

                    b.Property<int>("FkProductId")
                        .HasColumnType("int")
                        .HasColumnName("FK_ProductId");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("StockId")
                        .HasName("PK_StockId");

                    b.HasIndex("FkProductId");

                    b.ToTable("Stocks", "CentarProductMngt");
                });

            modelBuilder.Entity("Golfklubb_Centar_Webbshop.Models.Taxis", b =>
                {
                    b.Property<int>("TaxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaxId"));

                    b.Property<string>("TaxDescribtion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("TaxIndex")
                        .HasColumnType("int");

                    b.HasKey("TaxId")
                        .HasName("PK_TaxId");

                    b.ToTable("Taxes", "CentarOrderMngt");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", "CentarUserMngt");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "CentarUserMngt");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "CentarUserMngt");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogin", "CentarUserMngt");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "CentarUserMngt");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", "CentarUserMngt");
                });

            modelBuilder.Entity("Golfklubb_Centar_Webbshop.Models.CartItem", b =>
                {
                    b.HasOne("Golfklubb_Centar_Webbshop.Models.Cart", "FkCart")
                        .WithMany("CartItems")
                        .HasForeignKey("FkCartId")
                        .IsRequired()
                        .HasConstraintName("FK_CartItems_CartId");

                    b.HasOne("Golfklubb_Centar_Webbshop.Models.Product", "FkProduct")
                        .WithMany("CartItems")
                        .HasForeignKey("FkProductId")
                        .IsRequired()
                        .HasConstraintName("FK_CartItems_ProductId");

                    b.Navigation("FkCart");

                    b.Navigation("FkProduct");
                });

            modelBuilder.Entity("Golfklubb_Centar_Webbshop.Models.Category", b =>
                {
                    b.HasOne("Golfklubb_Centar_Webbshop.Models.Category", "FkParentCategory")
                        .WithMany("InverseFkParentCategory")
                        .HasForeignKey("FkParentCategoryId")
                        .HasConstraintName("FK_Categories_ParentCategoryId");

                    b.Navigation("FkParentCategory");
                });

            modelBuilder.Entity("Golfklubb_Centar_Webbshop.Models.Comment", b =>
                {
                    b.HasOne("Golfklubb_Centar_Webbshop.Models.Post", "FkPost")
                        .WithMany("Comments")
                        .HasForeignKey("FkPostId")
                        .IsRequired()
                        .HasConstraintName("FK_Comments_PostId");

                    b.HasOne("Golfklubb_Centar_Webbshop.Areas.Identity.Data.ApplicationUser", "FkUser")
                        .WithMany("Comments")
                        .HasForeignKey("FkUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Comments_UserId");

                    b.Navigation("FkPost");

                    b.Navigation("FkUser");
                });

            modelBuilder.Entity("Golfklubb_Centar_Webbshop.Models.History", b =>
                {
                    b.HasOne("Golfklubb_Centar_Webbshop.Models.Invoice", "FkInvoice")
                        .WithMany("Histories")
                        .HasForeignKey("FkInvoiceId")
                        .IsRequired()
                        .HasConstraintName("FK_Histories_InvoiceId");

                    b.HasOne("Golfklubb_Centar_Webbshop.Areas.Identity.Data.ApplicationUser", "FkUser")
                        .WithMany("Histories")
                        .HasForeignKey("FkUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Histories_UserId");

                    b.Navigation("FkInvoice");

                    b.Navigation("FkUser");
                });

            modelBuilder.Entity("Golfklubb_Centar_Webbshop.Models.Invoice", b =>
                {
                    b.HasOne("Golfklubb_Centar_Webbshop.Models.Order", "FkOrder")
                        .WithMany("Invoices")
                        .HasForeignKey("FkOrderId")
                        .IsRequired()
                        .HasConstraintName("FK_Invoices_OrderId");

                    b.HasOne("Golfklubb_Centar_Webbshop.Models.Payment", "FkPayment")
                        .WithMany("Invoices")
                        .HasForeignKey("FkPaymentId")
                        .HasConstraintName("FK_Invoices_PaymentId");

                    b.HasOne("Golfklubb_Centar_Webbshop.Models.Taxis", "FkTax")
                        .WithMany("Invoices")
                        .HasForeignKey("FkTaxId")
                        .IsRequired()
                        .HasConstraintName("FK_Invoices_TaxId");

                    b.HasOne("Golfklubb_Centar_Webbshop.Areas.Identity.Data.ApplicationUser", "FkUser")
                        .WithMany("Invoices")
                        .HasForeignKey("FkUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Invoices_UserId");

                    b.Navigation("FkOrder");

                    b.Navigation("FkPayment");

                    b.Navigation("FkTax");

                    b.Navigation("FkUser");
                });

            modelBuilder.Entity("Golfklubb_Centar_Webbshop.Models.InvoiceItem", b =>
                {
                    b.HasOne("Golfklubb_Centar_Webbshop.Models.Invoice", "FkInvoice")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("FkInvoiceId")
                        .IsRequired()
                        .HasConstraintName("FK_InvoiceItems_InvoiceId");

                    b.HasOne("Golfklubb_Centar_Webbshop.Models.Product", "FkProduct")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("FkProductId")
                        .IsRequired()
                        .HasConstraintName("FK_InvoiceItems_ProductId");

                    b.Navigation("FkInvoice");

                    b.Navigation("FkProduct");
                });

            modelBuilder.Entity("Golfklubb_Centar_Webbshop.Models.Order", b =>
                {
                    b.HasOne("Golfklubb_Centar_Webbshop.Models.Cart", "FkCart")
                        .WithMany("Orders")
                        .HasForeignKey("FkCartId")
                        .IsRequired()
                        .HasConstraintName("FK_Orders_CartId");

                    b.HasOne("Golfklubb_Centar_Webbshop.Areas.Identity.Data.ApplicationUser", "FkUser")
                        .WithMany("Orders")
                        .HasForeignKey("FkUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Orders_UserId");

                    b.Navigation("FkCart");

                    b.Navigation("FkUser");
                });

            modelBuilder.Entity("Golfklubb_Centar_Webbshop.Models.Payment", b =>
                {
                    b.HasOne("Golfklubb_Centar_Webbshop.Models.Order", "FkOrder")
                        .WithMany("Payments")
                        .HasForeignKey("FkOrderId")
                        .IsRequired()
                        .HasConstraintName("FK_Payments_OrderId");

                    b.Navigation("FkOrder");
                });

            modelBuilder.Entity("Golfklubb_Centar_Webbshop.Models.Post", b =>
                {
                    b.HasOne("Golfklubb_Centar_Webbshop.Areas.Identity.Data.ApplicationUser", "FkUser")
                        .WithMany("Posts")
                        .HasForeignKey("FkUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Posts_UserId");

                    b.Navigation("FkUser");
                });

            modelBuilder.Entity("Golfklubb_Centar_Webbshop.Models.Product", b =>
                {
                    b.HasOne("Golfklubb_Centar_Webbshop.Models.Category", "FkCategory")
                        .WithMany("Products")
                        .HasForeignKey("FkCategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Products_CategoryId");

                    b.HasOne("Golfklubb_Centar_Webbshop.Models.Discount", "FkDiscount")
                        .WithMany("Products")
                        .HasForeignKey("FkDiscountId")
                        .IsRequired()
                        .HasConstraintName("FK_Products_DiscountId");

                    b.Navigation("FkCategory");

                    b.Navigation("FkDiscount");
                });

            modelBuilder.Entity("Golfklubb_Centar_Webbshop.Models.ProductReview", b =>
                {
                    b.HasOne("Golfklubb_Centar_Webbshop.Models.Product", "FkProduct")
                        .WithMany("ProductReviews")
                        .HasForeignKey("FkProductId")
                        .IsRequired()
                        .HasConstraintName("FK_ProductReviews_ProductId");

                    b.HasOne("Golfklubb_Centar_Webbshop.Areas.Identity.Data.ApplicationUser", "FkUser")
                        .WithMany("ProductReviews")
                        .HasForeignKey("FkUserId")
                        .IsRequired()
                        .HasConstraintName("FK_ProductReviews_UserId");

                    b.Navigation("FkProduct");

                    b.Navigation("FkUser");
                });

            modelBuilder.Entity("Golfklubb_Centar_Webbshop.Models.Stock", b =>
                {
                    b.HasOne("Golfklubb_Centar_Webbshop.Models.Product", "FkProduct")
                        .WithMany("Stocks")
                        .HasForeignKey("FkProductId")
                        .IsRequired()
                        .HasConstraintName("FK_Stocks_ProductId");

                    b.Navigation("FkProduct");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Golfklubb_Centar_Webbshop.Areas.Identity.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Golfklubb_Centar_Webbshop.Areas.Identity.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Golfklubb_Centar_Webbshop.Areas.Identity.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Golfklubb_Centar_Webbshop.Areas.Identity.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Golfklubb_Centar_Webbshop.Areas.Identity.Data.ApplicationUser", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Histories");

                    b.Navigation("Invoices");

                    b.Navigation("Orders");

                    b.Navigation("Posts");

                    b.Navigation("ProductReviews");
                });

            modelBuilder.Entity("Golfklubb_Centar_Webbshop.Models.Cart", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Golfklubb_Centar_Webbshop.Models.Category", b =>
                {
                    b.Navigation("InverseFkParentCategory");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Golfklubb_Centar_Webbshop.Models.Discount", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Golfklubb_Centar_Webbshop.Models.Invoice", b =>
                {
                    b.Navigation("Histories");

                    b.Navigation("InvoiceItems");
                });

            modelBuilder.Entity("Golfklubb_Centar_Webbshop.Models.Order", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Golfklubb_Centar_Webbshop.Models.Payment", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("Golfklubb_Centar_Webbshop.Models.Post", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Golfklubb_Centar_Webbshop.Models.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("InvoiceItems");

                    b.Navigation("ProductReviews");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("Golfklubb_Centar_Webbshop.Models.Taxis", b =>
                {
                    b.Navigation("Invoices");
                });
#pragma warning restore 612, 618
        }
    }
}
